apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttc
  template:
    metadata:
      labels:
        app:ttc
    spec:
      containers:
      - image: okteto.dev/ttc:latest
        name: ttc
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f571cab6-d8ff-4d26-ab7d-0c12013943af"
        - name: Vless_Path
          value: "/urjei4jffsiw"
        - name: Vmess_UUID
          value: "f571cab6-d8ff-4d26-ab7d-0c12013943af"
        - name: Vmess_Path
          value: "/ugrtrrosrj45j"
        - name: Share_Path
          value: "/v2link"
